-- dolphin
-- GRANT

-- 创建用户
CREATE USER IF NOT EXISTS user1 IDENTIFIED BY 'test-1234';。
CREATE USER IF NOT EXISTS user2 IDENTIFIED BY 'test-1234';。

-- 授权用户
GRANT CREATE ANY FUNCTION TO user1;。
GRANT CREATE TEMPORARY TABLES ON DATABASE proto_test_db TO user1;。
GRANT INDEX ON *.* TO user1;。

-- 将 user1 授权给 user2
GRANT user1 TO user2;。

-- 创建并授权新用户
GRANT USAGE ON *.* TO new_user IDENTIFIED BY 'test-1234';。
GRANT USAGE ON *.* TO new_user IDENTIFIED BY 'new_password-1234';。

-- 销毁权限
REVOKE ALL PRIVILEGES FROM user1;。
REVOKE ALL PRIVILEGES FROM user2;。
REVOKE ALL PRIVILEGES FROM new_user;。

-- 删除用户
DROP USER IF EXISTS user1 CASCADE;。
DROP USER IF EXISTS user2 CASCADE;。
DROP USER IF EXISTS new_user CASCADE;。

-- 清理
DROP FUNCTION IF EXISTS TEST;。
