{
 "title": "mysql2opengauss",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "迁移数量",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\nUNIX_TIMESTAMP(proctime) AS time_sec,\r\n  '数据库数量' AS metric,\r\n  count(*) AS '数据库数量' \r\nFROM db_info_metrics\r\n WHERE\r\n $__timeFilter(proctime) group by metric;\r\n "
    },
    {
     "rawSql": "SELECT\r\nUNIX_TIMESTAMP(proctime) AS time_sec,\r\n  '表数量' AS metric,\r\n  sum(tablecount) AS '表数量' \r\nFROM db_info_metrics\r\n WHERE\r\n $__timeFilter(proctime) group by metric;\r\n "
    },
    {
     "rawSql": "SELECT\r\nUNIX_TIMESTAMP(proctime) AS time_sec,\r\n  '视图数量' AS metric,\r\n  sum(viewcount) AS '视图数量' \r\nFROM db_info_metrics\r\n WHERE\r\n $__timeFilter(proctime) group by metric;\r\n "
    },
    {
     "rawSql": "SELECT\r\nUNIX_TIMESTAMP(proctime) AS time_sec,\r\n  '存储过程数量' AS metric,\r\n  sum(procedurecount) AS '存储过程数量' \r\nFROM db_info_metrics WHERE\r\n $__timeFilter(proctime) group by metric;\r\n "
    },
    {
     "rawSql": "SELECT\r\nUNIX_TIMESTAMP(proctime) AS time_sec,\r\n  '函数数量' AS metric,\r\n  sum(functioncount) AS '函数数量' \r\nFROM db_info_metrics WHERE\r\n $__timeFilter(proctime) group by metric;\r\n "
    }
   ]
  },
  {
   "title": "执行语句情况",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  '执行正确语句数量' AS metric,\r\n  sum(rightcount) AS '执行正确语句数量' \r\nFROM db_info_metrics\r\n WHERE\r\n $__timeFilter(proctime);\r\n "
    },
    {
     "rawSql": "SELECT\r\n  '执行错误语句数量' AS metric,\r\n  sum(errorcount) AS '执行错误语句数量' \r\nFROM db_info_metrics\r\n WHERE\r\n $__timeFilter(proctime);\r\n "
    }
   ]
  },
  {
   "title": "插入数据量",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  proctime AS time,\r\n  concat(concat(srcaddr, srcdb), tablename) as series,\r\n  insertrightcount AS value \r\nFROM table_info_metrics\r\n WHERE\r\n $__timeFilter(proctime)\r\norder by value desc;\r\n "
    }
   ]
  },
  {
   "title": "耗时情况(毫秒)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  proctime AS time,\r\n  concat(concat(srcaddr, srcdb), tablename) as series,\r\n  consumetime AS value \r\nFROM table_info_metrics\r\n WHERE\r\n $__timeFilter(proctime)\r\norder by value desc;\r\n "
    }
   ]
  },
  { "title": "基本信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "最近两个数据库的迁移数量",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(A.updatetime, $__interval),\r\n  concat(A.srcdb, '表') AS metric,\r\n  A.tablecount AS value \r\nFROM time_db_info_metrics A, (select srcdb from time_db_info_metrics group by proctime, srcdb order by updatetime desc limit 2) B\r\n WHERE\r\n $__timeFilter(A.updatetime) and \r\n A.srcdb = B.srcdb\r\n ORDER BY A.updatetime;\r\n "
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(A.updatetime, $__interval),\r\n  concat(A.srcdb, '视图') AS metric,\r\n  A.viewcount AS value \r\nFROM time_db_info_metrics A, (select srcdb from time_db_info_metrics group by proctime, srcdb order by updatetime desc limit 2) B\r\n WHERE\r\n $__timeFilter(A.updatetime) and \r\n A.srcdb = B.srcdb\r\n ORDER BY A.updatetime;\r\n "
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(A.updatetime, $__interval),\r\n  concat(A.srcdb, '过程') AS metric,\r\n  A.procedurecount AS value \r\nFROM time_db_info_metrics A, (select srcdb from time_db_info_metrics group by proctime, srcdb order by updatetime desc limit 2) B\r\n WHERE\r\n $__timeFilter(A.updatetime) and \r\n A.srcdb = B.srcdb\r\n ORDER BY A.updatetime;\r\n "
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(A.updatetime, $__interval),\r\n  concat(A.srcdb, '函数') AS metric,\r\n  A.functioncount AS value \r\nFROM time_db_info_metrics A, (select srcdb from time_db_info_metrics group by proctime, srcdb order by updatetime desc limit 2) B\r\n WHERE\r\n $__timeFilter(A.updatetime) and \r\n A.srcdb = B.srcdb\r\n ORDER BY A.updatetime;\r\n "
    }
   ]
  },
  {
   "title": "最近两个数据库的迁移语句执行数量",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(A.updatetime) AS time_sec,\r\n  concat(A.srcdb, '总数') AS metric,\r\n  A.totalcount AS value \r\nFROM time_db_info_metrics A, (select srcdb from time_db_info_metrics group by proctime, srcdb order by updatetime desc limit 2) B\r\n WHERE\r\n $__timeFilter(updatetime) and \r\n A.srcdb = B.srcdb\r\n ORDER BY A.updatetime;\r\n "
    },
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(A.updatetime) AS time_sec,\r\n  concat(A.srcdb, '错误数') AS metric,\r\n  A.errorcount AS value \r\nFROM time_db_info_metrics A, (select srcdb from time_db_info_metrics group by proctime, srcdb order by updatetime desc limit 2) B\r\n WHERE\r\n $__timeFilter(updatetime) and \r\n A.srcdb = B.srcdb\r\n ORDER BY A.updatetime;\r\n "
    }
   ]
  },
  { "title": "详细信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "错误最多的数据库",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_sub(proctime, interval 8 hour) AS \"迁移时间\",\n  srcdb AS \"源数据库\",\n  dstdb AS \"目的数据库\",\n  errorcount AS \"错误语句总数\",\n  totalcount AS \"执行语句总数\",\n  rightcount AS \"正确语句总数\",\n  insertrightcount AS \"正确插入数据总量\",\n  inserterrorcount AS \"错误插入数据总量\",\n  consumetime AS \"迁移耗时（毫秒）\",\n  srcaddr AS \"源数据库地址\",\n  dstaddr AS \"目的数据库地址\",\n  date_sub(starttime, interval 8 hour) AS \"开始时间\",\n  date_sub(endtime, interval 8 hour) AS \"结束时间\"\nFROM db_info_metrics\nWHERE\n  $__timeFilter(starttime)\nORDER BY errorcount desc,srcdb asc limit 10"
    }
   ]
  },
  {
   "title": "迁移耗时最长的数据库",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_sub(proctime, interval 8 hour) AS \"迁移时间\",\n  srcdb AS \"源数据库\",\n  dstdb AS \"目的数据库\",\n  consumetime AS \"迁移耗时（毫秒）\",\n  totalcount AS \"执行语句总数\",\n  rightcount AS \"正确语句总数\",\n  errorcount AS \"错误语句总数\",\n  insertrightcount AS \"正确插入数据总量\",\n  inserterrorcount AS \"错误插入数据总量\",\n  srcaddr AS \"源数据库地址\",\n  dstaddr AS \"目的数据库地址\",\n  date_sub(starttime, interval 8 hour) AS \"开始时间\",\n  date_sub(endtime, interval 8 hour) AS \"结束时间\"\nFROM db_info_metrics\nWHERE\n  $__timeFilter(starttime)\nORDER BY consumetime desc,srcdb asc limit 10"
    }
   ]
  },
  {
   "title": "错误最多的表",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_sub(proctime, interval 8 hour) AS \"迁移时间\",\n  tablename AS \"表名\",\n  errorcount AS \"错误语句总数\",\n  totalcount AS \"执行语句总数\",\n  rightcount AS \"正确语句总数\",\n  insertrightcount AS \"正确插入数据总量\",\n  inserterrorcount AS \"错误插入数据总量\",\n  srcdb AS \"源数据库\",\n  dstdb AS \"目的数据库\",\n  consumetime AS \"迁移耗时（毫秒）\",\n  srcaddr AS \"源数据库地址\",\n  dstaddr AS \"目的数据库地址\",\n  date_sub(starttime, interval 8 hour) AS \"开始时间\",\n  date_sub(endtime, interval 8 hour) AS \"结束时间\"\nFROM table_info_metrics\nWHERE\n  $__timeFilter(starttime)\nORDER BY errorcount desc,tablename asc limit 10"
    }
   ]
  },
  {
   "title": "迁移耗时最长的表",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_sub(proctime, interval 8 hour) AS \"迁移时间\",\n  tablename AS \"表名\",\n  consumetime AS \"迁移耗时（毫秒）\",\n  srcdb AS \"源数据库\",\n  dstdb AS \"目的数据库\",\n  totalcount AS \"执行语句总数\",\n  rightcount AS \"正确语句总数\",\n  errorcount AS \"错误语句总数\",\n  insertrightcount AS \"正确插入数据总量\",\n  inserterrorcount AS \"错误插入数据总量\",\n  srcaddr AS \"源数据库地址\",\n  dstaddr AS \"目的数据库地址\",\n  date_sub(starttime, interval 8 hour) AS \"开始时间\",\n  date_sub(endtime, interval 8 hour) AS \"结束时间\"\nFROM table_info_metrics\nWHERE\n  $__timeFilter(starttime)\nORDER BY consumetime desc, tablename asc limit 10"
    }
   ]
  },
  {
   "title": "最近的sql错误",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_sub(proctime, interval 8 hour) AS \"迁移时间\",\n  name AS \"名称\",\n  type AS \"类型\",\n  errorinfo AS \"错误信息\",\n  sqldata AS \"sql语句\",\n  srcaddr AS \"源数据库地址\",\n  dstaddr AS \"目的数据库地址\",\n  srcdb AS \"源数据库\",\n  dstdb AS \"目的数据库\",\n  date_sub(starttime, interval 8 hour) AS \"开始时间\",\n  date_sub(endtime, interval 8 hour) AS \"结束时间\",\n  consumetime AS \"执行耗时（毫秒）\"\nFROM sql_info_metrics\nWHERE\n  $__timeFilter(starttime)\nORDER BY starttime desc, name asc limit 20"
    }
   ]
  }
 ]
}