[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "airbyte-destination-opengauss-datavec"
version = "0.1.0"
description = "Airbyte destination implementation for OpenGauss with vector support"
authors = ["hly <liyanhu03@163.com>"]
license = "MIT"
readme = "README.md"

[[tool.poetry.packages]]
include = "destination_opengauss_datavec"

[tool.poetry.dependencies.airbyte-cdk]
# Version constrained by PyAirbyte (`airbyte`) version
version = ">=1.0"
extras = ["vector-db-based"]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"

airbyte = "^0.12.0"
sqlalchemy = "<2.0"
opengauss-sqlalchemy = { git = "https://gitcode.com/opengauss/openGauss-sqlalchemy.git", rev = "da80fc05ebc105968bdebfd4d0614776ad83d5fe" }
psycopg2-binary = "2.9.9"
jaraco-functools = "^4.1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
ruff = "^0.3.2"
mypy = "^1.9.0"
coverage = "^7.5.3"

[tool.poetry.scripts]
destination-opengauss-datavec = "destination_opengauss_datavec.run:run"

[tool.ruff]
target-version = "py310"
preview = true
line-length = 100

[[tool.mypy.overrides]]
module = [
    "airbyte_protocol",
    "airbyte_protocol.*",
    "sqlalchemy",
    "sqlalchemy.*",
    "opengauss_sqlalchemy",
    "opengauss_sqlalchemy.*",
    "dpath",
    "dpath.util",
]
ignore_missing_imports = true    # No stubs yet (😢)

[tool.coverage.run]
# branch = true
# parallel = true
omit = [
    "unit_tests/*",
    "integration_tests/*",
    "destination_opengauss_datavec/common/*",
]

[tool.coverage.report]
precision = 1
fail_under = 90.0
exclude_also = [
    # # TYPE_CHECKING block is only executed while running mypy
    "if TYPE_CHECKING:",
    "\\.\\.\\."
]

[tool.poe]
include = [
    # Shared tasks definition file(s) can be imported here.
    # Run `poe` or `poe --help` to see the list of available tasks.
    "${POE_GIT_DIR}/poe-tasks/poetry-connector-tasks.toml",
]
