# Letta-OpenGauss RAG系统 Docker Compose配置
# 包含OpenGauss数据库和Letta服务器的完整栈

version: '3.8'

services:
  # OpenGauss向量数据库
  opengauss:
    image: opengauss/opengauss:latest
    container_name: letta-opengauss-db
    environment:
      - GS_PASSWORD=${LETTA_PG_PASSWORD:-OpenGauss@123}
      - GS_DB=${LETTA_PG_DB:-letta}
      - GS_USER=${LETTA_PG_USER:-opengauss}
    ports:
      - "${LETTA_PG_PORT:-5432}:5432"
    volumes:
      - opengauss_data:/var/lib/opengauss/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep gaussdb | grep -v grep || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - letta-network
      
  # Letta服务器
  letta-server:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - LETTA_VERSION=${LETTA_VERSION:-latest}
    container_name: letta-server
    depends_on:
      opengauss:
        condition: service_healthy
      # bge-embedding:
      #   condition: service_healthy
      # vllm-service:
      #   condition: service_healthy
    ports:
      - "${LETTA_SERVER_PORT:-8283}:8283"
      - "4317:4317"  # OpenTelemetry gRPC
      - "4318:4318"  # OpenTelemetry HTTP
    env_file:
      - .env
    environment:
      # 数据库配置
      - LETTA_ENABLE_OPENGAUSS=true
      - LETTA_PG_HOST=opengauss
      - LETTA_PG_PORT=5432
      - LETTA_PG_DB=${LETTA_PG_DB:-letta}
      - LETTA_PG_USER=${LETTA_PG_USER:-opengauss}
      - LETTA_PG_PASSWORD=${LETTA_PG_PASSWORD:-OpenGauss@123}
      
      # API配置 (支持宿主机服务)
      - OPENAI_API_BASE=${OPENAI_API_BASE:-http://host.docker.internal:8000/v1}
      - BGE_API_BASE=${BGE_API_BASE:-http://host.docker.internal:8003/v1}
      - VLLM_API_BASE=${VLLM_API_BASE:-http://host.docker.internal:8000/v1}
      
      # 其他配置
      - LETTA_DEBUG=${LETTA_DEBUG:-false}
      - HOST=0.0.0.0
      - PORT=8283
    volumes:
      - letta_logs:/app/logs
      - letta_data:/app/data
      - ./reports:/app/reports
      - ./templates:/app/templates
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8283/v1/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    extra_hosts:
      - "host.docker.internal:host-gateway"  # 确保跨平台兼容性
    networks:
      - letta-network

# 数据卷
volumes:
  opengauss_data:
    driver: local
  letta_logs:
    driver: local
  letta_data:
    driver: local

# 网络
networks:
  letta-network:
    driver: bridge