[project]
name = "finrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "huggingface-hub>=0.35.2",
    "pandas>=2.3.2",
    "pyarrow>=21.0.0",
]
